// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetUser() {
  return window['go']['backend']['App']['GreetUser']();
}

export function SaveName(arg1) {
  return window['go']['backend']['App']['SaveName'](arg1);
}
