// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getUserPreference = `-- name: GetUserPreference :one
SELECT value FROM user_preferences
WHERE key = ? LIMIT 1
`

func (q *Queries) GetUserPreference(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getUserPreferenceStmt, getUserPreference, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setUserPreference = `-- name: SetUserPreference :exec
INSERT INTO user_preferences (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetUserPreferenceParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetUserPreference(ctx context.Context, arg SetUserPreferenceParams) error {
	_, err := q.exec(ctx, q.setUserPreferenceStmt, setUserPreference, arg.Key, arg.Value)
	return err
}
